### PR TITLE
flutter_assignment

### PR DESCRIPTION
**Pull request by rimi-s**
flutter -assingment

### CODE REVIEW

**Comment by rimi-s** [comment]
please see the code in **lib** folder 
all the files related to flutter assignment is there in lib folder

**Comment by zeroolatency** [comment]
Hi @rimi-s, thanks for attempting the assignment. Can you please revert on the assignment mail with the github repo of your submission?

Since this PR can be seen by everyone, I'll be removing it from here to make sure everyone is evaluated fairly. Thanks!

**Comment by rimi-s** [comment]
okay sure
here is the link
https://github.com/lalit-eai/flutter-assignment/pull/1/commits/0116a27f82b8bf8f37a44a0a3ce62957e59262ca
https://github.com/lalit-eai/flutter-assignment/pull/1/commits/0116a27f82b8bf8f37a44a0a3ce62957e59262ca#diff-e61eb31d013d12616f5532636a88cfa63631dda8f7829e5424e68542214d1608

thanks

**Comment by zeroolatency** [comment]
Hi @rimi-s, can you share your email ID and your mobile number so that we can schedule a call with you?

**Comment by rimi-s** [comment]
Hii

Sure, here it is
***@***.***
Mob No: 8416978598
LinkedIn ID: https://www.linkedin.com/in/dezi-shrivastav-85a8b515b
Please feel free to reach out to me.

Thanks & Regards
Dezi Shrivastav

**Pull request closed without merging**
